{
 "title": "APC UPS",
 "tags": [ "apcupsd" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Time On Battery",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "Cumulative Time On Battery",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_cumulative_time_on_seconds_total"
    }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Battery Charge Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_charge_percent", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "UPS Load Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_ups_load_percent", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_nominal_volts", "legendFormat": "nominal" },
    { "expr": "apcupsd_battery_volts", "legendFormat": "actual" }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_line_nominal_volts", "legendFormat": "nominal" },
    { "expr": "apcupsd_line_volts", "legendFormat": "actual" }
   ]
  }
 ]
}